-- Audit / soft-delete columns from BaseEntity (one ADD per statement for H2 + PG)
ALTER TABLE users ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN registration_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ADD COLUMN update_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ADD COLUMN exclusion_date TIMESTAMP WITH TIME ZONE;

ALTER TABLE rackets ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE rackets ADD COLUMN registration_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE rackets ADD COLUMN update_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE rackets ADD COLUMN exclusion_date TIMESTAMP WITH TIME ZONE;

ALTER TABLE play_sessions ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE play_sessions ADD COLUMN registration_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE play_sessions ADD COLUMN update_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE play_sessions ADD COLUMN exclusion_date TIMESTAMP WITH TIME ZONE;
